[package]
name = "PolyView Browser"
version = "1.0.0"
description = "A browser built with PolyView - iframe2 that bypasses all restrictions"

[window]
width = 1280
height = 800
decorations = false
resizable = true

[dev]
inject_alpine = false
inject_lucide = false
